""" Constants for brrr.now """

# DEFAULTS
DEFAULT_REQUEST_TIMEOUT = 5
DEFAULT_VERIFY_SSL = True
DEFAULT_ALLOW_TOPIC_OVERRIDE = False
DEFAULT_ATTACHMENT_MAXSIZE = 15728640

# CONFIG
CONF_TOKEN = 'token'
CONF_ATTACHMENT_MAXSIZE = 'attachment_maxsize'
